name: Backend Deployment

on:
  workflow_dispatch:

jobs:

  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: backend/.
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
          
  test-deploy:
    needs: test-build
    runs-on: ubuntu-latest
    steps:  
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker rm -f backend || true
            docker image rm ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest || true
            docker run -d --restart always -p 8080:8080 --name backend \
              --env MONGO_USERNAME=${{ secrets.MONGO_USERNAME }} \
              --env MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
              --env MONGO_CONTAINER_NAME=mongo \
              --env MONGO_PORT=27017 \
              ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest || true
            docker network connect database backend || true