name: Frontend Deployment

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: frontend/.
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
          build-args: |
            REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:  
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo docker rm -f frontend || true
            sudo docker image rm ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest || true
            sudo docker run -d -p 3000:3000 --name frontend ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest || true